# Generated by Django 2.2.7 on 2019-11-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk_langsa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyawan',
            old_name='NoHp',
            new_name='No_HP',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='UnitKerja',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='Unit_Kerja',
            field=models.IntegerField(choices=[(1, 'Kepesertaan'), (2, 'Pelayanan'), (3, 'Keuangan'), (4, 'Umum & SDM')], default=1),
            preserve_default=False,
        ),
    ]
