# Generated by Django 2.2.7 on 2019-11-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pk_langsa', '0002_auto_20191114_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persekot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('tgl_pk', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='karyawan',
            old_name='Nama',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='karyawan',
            old_name='No_HP',
            new_name='no_hp',
        ),
        migrations.RenameField(
            model_name='karyawan',
            old_name='NPK',
            new_name='npk',
        ),
        migrations.RenameField(
            model_name='karyawan',
            old_name='Unit_Kerja',
            new_name='unit_kerja',
        ),
        migrations.CreateModel(
            name='PetanggungJawabanPersekot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_selesai_pk', models.DateField()),
                ('persekot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pk_langsa.Persekot')),
            ],
        ),
        migrations.AddField(
            model_name='persekot',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pk_langsa.Karyawan'),
        ),
    ]
